"""add in_app_notifications table

Revision ID: add_in_app_notifications
Revises: 1d9a002d7234
Create Date: 2026-03-05 21:45:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "add_in_app_notifications"
down_revision = "1d9a002d7234"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "in_app_notifications",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("notification_type", sa.String(), nullable=False),
        sa.Column("data", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_in_app_notifications_notification_type"), "in_app_notifications", ["notification_type"], unique=False
    )
    op.create_index(op.f("ix_in_app_notifications_read_at"), "in_app_notifications", ["read_at"], unique=False)
    op.create_index(op.f("ix_in_app_notifications_user_id"), "in_app_notifications", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_in_app_notifications_user_id"), table_name="in_app_notifications")
    op.drop_index(op.f("ix_in_app_notifications_read_at"), table_name="in_app_notifications")
    op.drop_index(op.f("ix_in_app_notifications_notification_type"), table_name="in_app_notifications")
    op.drop_table("in_app_notifications")
    # ### end Alembic commands ###
